In [4]:
import scipy.io as sio
import numpy as np
from data_helper import file_list, data_folder, cv_folder

In [6]:
file_name = 'australian'

In [13]:
D = np.loadtxt("{}\{}.dat".format(data_folder, file_name), delimiter=',')
cv = sio.loadmat("{}\cv_{}.mat".format(cv_folder, file_name))['cv']
cv

array([[array([[  6],
       [ 36],
       [ 41],
       [ 68],
       [ 82],
       [ 83],
       [ 86],
       [107],
       [110],
       [122],
       [133],
       [144],
       [152],
       [155],
       [158],
       [160],
       [176],
       [189],
       [201],
       [213],
       [220],
       [223],
       [232],
       [266],
       [268],
       [278],
       [290],
       [310],
       [321],
       [326],
       [328],
       [343],
       [355],
       [362],
       [373],
       [385],
       [386],
       [394],
       [395],
       [399],
       [419],
       [424],
       [430],
       [434],
       [438],
       [444],
       [451],
       [467],
       [494],
       [495],
       [499],
       [510],
       [514],
       [519],
       [540],
       [541],
       [561],
       [566],
       [572],
       [581],
       [584],
       [596],
       [619],
       [636],
       [643],
       [652],
       [662],
       [667],
       [668]], dtype=uint16),
        ar

In [21]:
cv[0,1][:,0] - 1 

array([  0,   2,   5,  14,  16,  34,  39,  44,  53,  73,  85,  86,  96,
       104, 116, 134, 156, 165, 171, 177, 186, 188, 210, 215, 239, 253,
       277, 280, 291, 292, 308, 379, 385, 389, 405, 408, 409, 416, 418,
       428, 429, 446, 454, 465, 467, 468, 475, 498, 506, 509, 510, 522,
       524, 525, 528, 537, 550, 557, 573, 591, 598, 602, 639, 642, 643,
       647, 654, 660, 687], dtype=uint16)

In [35]:
import numpy as np
Y = [1,2 ,1,2,2,1,3,3,3]
W = np.zeros((9,3))
for i0 in range(9):
    for m in range(3):
        if Y[i0] == m+1:
            W[i0][m] = 1
W

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [76]:
a = np.random.rand(8,2)
a

array([[0.08393037, 0.48438296],
       [0.06801243, 0.77459977],
       [0.72342298, 0.08493537],
       [0.58516777, 0.72578027],
       [0.21411868, 0.41512959],
       [0.82227796, 0.82003789],
       [0.23152848, 0.74378095],
       [0.71831966, 0.97589164]])

In [88]:
b = [1,0,0,1,0,1,1,0]
from scipy.optimize import lsq_linear
W = lsq_linear(a, b)
W

 active_mask: array([0., 0.])
        cost: 0.9625497656138279
         fun: array([-0.65559936,  0.5452808 ,  0.11890867, -0.44602958,  0.30690154,
       -0.36078162, -0.46268897,  0.73921795])
     message: 'The unconstrained solution is optimal.'
         nit: 0
  optimality: 3.3306690738754696e-16
      status: 3
     success: True
           x: array([0.08257142, 0.69670162])